# basic github workflow
#
# this will be trigger on each commit
#
name: Test
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Grentenrg/test-simple-gh-action-2@main
        with:
          who-to-greet: Mona the Octocat
